# General cluster-level information
cluster:
  # Used in custom-ca.yaml
  ca:
    # true if you have a cert and want to set it, false to skip setting a cluster ca.
    specify: true
    content: |- # The cluster's CA
      ----- CA Content ------
      ......
      ----- end content ----
  # Used in:
  #  - ingress-certs-secret.yaml
  #  - ingress-controller.yaml
  ingress:
    secretName: ingress-cert
    cert: |-
      ---- cert content ----
      ....
      ---- content ------
    key:
      ----- cert content ----
      .....
      ----- cert content ----
# TODO:: doublecheck updated from site
# Configuration for NodeNetworkConfigurationPolicy
# Used in:
#  - nncps.yaml
#  - nncp-bond.yaml ?
nncps:
  - name: master-0
    vlans:
      - id: 1 # TODO:: specify, int
        ip: 192.168.1.1 # TODO:: specify
#  - name: worker-1
#    vlans:
#      - id: 2 # TODO:: specify, int
#        ip: 192.168.1.2 # TODO:: specify
  # ... TODO:: fill out

# LDAP configuration.
# Used in:
#  - ldap-accounts.yaml
#  - ldap-bind-secret.yaml
#  - ocp-oauth-sec.yaml
ldap:
  # The name of the LDAPSyncConfig (ldap-accounts.yaml)
  syncConfigName: foo
  accountName: sAMAccountName
  bindDN: # like some.svc.ocp
  bindPW: foo # plaintext
  server:
    name: # like NAME LDAP
    urlFull: # like: ldap://fdqn/dn?accountName
    urlShort: # like: ldap://fdqn
  groupUIDNameMapping: # Like "cn=foo,ou=bar..."
  queries:
    group:
      baseDN: # Like "cn=foo,ou=bar..."
    user:
      baseDN: # Like "cn=foo,ou=bar..."
      filter: # Like "(cn=foo,ou=bar...)"

# Chrony configuration.
# Used in:
#  - chrony-configuration.yaml
chrony:
  roles:
    - role: master
    - role: worker
  configContent: |-
    # content of chrony config

# Storage settings for the cluster.
# Used in ocp-trident.yaml
storage:
  provisioner: #IP/hostname
