cluster:
  ca:
    specify: true
    configMapName: cluster-ca
    content: |- # The cluster's CA
      ----- CA Content ------
      ......
      ----- end content ----
  ingress:
    secretName: ingress-cert
    cert: |-
      ---- cert content ----
      ....
      ---- content ------
    key:
      ----- cert content ----
      .....
      ----- cert content ----
nncps:
  bond:
    name: bond0
    bond:
      ports:
        - ens2f0
        - ens3f0  
        # etc
    vlans:
      - id: 677
      # etc
  nodes:
    - name: master-0
      vlans:
        - id: 1 # TODO:: specify, int
          ip: 192.168.1.1 # TODO:: specify
#  - name: worker-1
#    vlans:
#      - id: 2 # TODO:: specify, int
#        ip: 192.168.1.2 # TODO:: specify
  # ... TODO:: fill out

ldap:
  syncConfigName: foo
  accountName: sAMAccountName
  bindDN: # like some.svc.ocp
  bindPW: foo # plaintext
  server:
    name: # like NAME LDAP
    urlFull: # like: ldap://fdqn/dn?accountName
    urlShort: # like: ldap://fdqn
  groupUIDNameMappingKey: # Like "cn=foo,ou=bar..."
  queries:
    group:
      baseDN: # Like "cn=foo,ou=bar..."
    user:
      baseDN: # Like "cn=foo,ou=bar..."
      filter: # Like "(cn=foo,ou=bar...)"

chrony:
  roles:
    - role: master
    - role: worker
  configContent: |-
    # content of chrony config

storage:
  provisioner: #IP/hostname
