cluster:
  ca:
    specify: false
    content: |- # The cluster's CA
      ----- CA Content ------
      ......
      ----- end content ----
nncps:
  - name: master-0
    vlans:
      - id: 1 # TODO:: specify, int
        ip: 192.168.1.42 # TODO:: specify
#  - name: worker-1
#    vlans:
#      - id: 2 # TODO:: specify, int
#        ip: 192.168.1.2 # TODO:: specify
  # ... TODO:: fill out

ldap:
  syncConfigName: foo
  accountName: sAMAccountName
  bindDN: # like some.svc.ocp
  bindPW: foo # plaintext
  server:
    name: # like NAME LDAP
    urlFull: # like: ldap://fdqn/dn?accountName
    urlShort: # like: ldap://fdqn
  groupUIDNameMapping: cn=foo,ou=bar # Like "cn=foo,ou=bar..."
  queries:
    group:
      baseDN: # Like "cn=foo,ou=bar..."
    user:
      baseDN: # Like "cn=foo,ou=bar..."
      filter: # Like "(cn=foo,ou=bar...)"

chrony:
  configContent: |-
    # content of chrony config

storage:
  provisioner: #IP/hostname