# Common
common_git_repos:
  - "https://github.com/cjnovak98/ocp4-disconnected-collection.git"
  - "https://github.com/cjnovak98/ocp4-disconnected-config"

common_openshift_cluster_install_dir:  "{{ common_install_dir }}/install"
common_openshift_dir: /pods/content
common_connected_cluster: false
mirror_content_pull_mirror: false

common_openshift_interface: ens1
common_fips_enabled: true
common_cluster_domain: example.com

common_ip_space: 192.168.122
common_nodes:
  - name: master-0
    ip: '42'
    mac: 52:54:00:8d:13:77
  - name: worker-0
    ip: '43'
    mac: 52:54:00:8d:13:78

# Registry
#common_registry_volume: /pods/registry
#registry_username: openshift
#registry_password: CHANGEME


# iDRAC
#idrac: false  ### NEED TO WRITE LOGIC/REMOVE THIS VAR. MAKE IT SMARTER!!!
#idrac_user: test
#idrac_password: tester

media_share_idracs:
  - name: master-0
    ip: '{{ ip_space }}.5'
  - name: worker-0
    ip: '{{ ip_space }}.8'

# Single Node Worker

#worker_iso_disk_type: sda

# Configure vlans (for managment networks on nodes for HA deployment or Single node Master only)

#################################
#### NEED TO CONVERT TO HELM#####
#################################
#bond_name: bond0
#bond_mode: 802.3ad
#bond_interfaces:
#  - name: eno1
#  - name: eno2
#  - name: eno3
#  - name: eno4
#vlans:
#  - id: 111
#    ip: 10.11.1
#  - id: 112
#    ip: 10.11.2
