apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.opeshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    release.openshift.io/create-only: 'true'
spec:
  identityProviders:
    - ldap:
      attributes:
        email:
        - mail
        id:
        - {{ .Values.ldap.accountName }}
        name:
        - displayName
          preferredUsername
        - {{ .Values.ldap.accountName }}
      bindDN: {{ .Values.ldap.bindDN }}
      bindPassword:
        name: ldap-bind-password
      insecure: true
      url: {{ .Values.ldap.server.urlFull }}
      mappingMethod: claim
      name: {{ .Values.ldap.server.name }}
      type: LDAP