gitOps:
  namespace: openshift-gitops

gitRepoTemplate:
  url: git@192.168.122.42:repos
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----
icsp:
  operator-0:
    labels:
      operators.openshift.org/catelog: "true"
    mirrors:
    - mirrors:
      - fqdn.lab/quay
      source: registry.redhat.io/quay
  release-0:
    mirrors:
    - mirrors:
      - fqdn.lab/quay
      source: registry.redhat.io/quay
