gitOps:
  namespace: openshift-gitops
  source: redhat-operators

gitRepoTemplate:
  # The URL of the repository setup in the Ansible step.
  url: git@<ip of host>:repos
  # The SSH key of the user that ran the Ansible step, used to connect to the git repo
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----
icsp:
  operator-0:
    labels:
      operators.openshift.org/catelog: "true"
    mirrors:
    - mirrors:
      - fqdn.lab/quay
      source: registry.redhat.io/quay