{{- range $policyName, $v := .Values.icsp }}
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catelog: "true"
  name: {{ $policyName }}
spec:
  repositoryDigestMirrors:
{{ toYaml $v.mirrors | indent 2 }}
{{- end }}
