apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bond0-bridge-vlan58 
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "bond0-bridge-vlan672", 
    "type": "bridge", 
    "bridge": "bond0-br0", 
    "macspoofchk": false, 
    "vlan": 672,
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "192.168.10.10/24"
        }
      ]
    }
  }'