apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: trident-vlan672 
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "bond0-bridge-vlan672", 
    "type": "bridge", 
    "bridge": "br-bond0.672", 
    "macspoofchk": false, 
    "vlan": 672,
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "192.168.72.2/24"
        }
      ]
    }
  }'