apiVersion: v1
items:
- apiVersion: nmstate.io/v1
  kind: NodeNetworkConfigurationPolicy
  metadata:
    name: bond-ips
  spec:
    desiredState:
      interfaces:
      - ipv4:
          address:
          - ip: {{ ip0 }}
            prefix-length: 24
          dhcp: false
          enabled: true
        name: bond0.670
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 670
      - ipv4:
          address:
          - ip: {{ ip0 }}
            prefix-length: 24
          dhcp: false
          enabled: true
        name: bond0.672
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 672
    nodeSelector:
      kubernetes.io/hostname: master-0
- apiVersion: nmstate.io/v1
  kind: NodeNetworkConfigurationPolicy
  metadata:
    name: bond-ips-1
  spec:
    desiredState:
      interfaces:
      - ipv4:
          address:
          - ip: {{ ip1 }}
            prefix-length: 24
          dhcp: false
          enabled: true
        name: bond0.670
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 670
      - ipv4:
          address:
          - ip: {{ ip1 }}
            prefix-length: 24
          dhcp: false
          enabled: true
        name: bond0.672
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 672
    nodeSelector:
      kubernetes.io/hostname: master-1
- apiVersion: nmstate.io/v1
  kind: NodeNetworkConfigurationPolicy
  metadata:
    name: bond-ips-2
  spec:
    desiredState:
      interfaces:
      - ipv4:
          address:
          - ip: {{ ip2 }}
            prefix-length: 24
          dhcp: false
          enabled: true
        name: bond0.670
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 670
      - ipv4:
          address:
          - ip: {{ ip2 }}
            prefix-length: 24
          dhcp: false
          enabled: true
        name: bond0.672
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 672
    nodeSelector:
      kubernetes.io/hostname: master-2
- apiVersion: nmstate.io/v1
  kind: NodeNetworkConfigurationPolicy
  metadata:
    name: bond-ips-3
  spec:
    desiredState:
      interfaces:
      - ipv4:
          address:
          - ip: {{ ip3 }}
            prefix-length: 24
          dhcp: false
          enabled: true
        name: bond0.670
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 670
      - ipv4:
          address:
          - ip: {{ ip3 }}
            prefix-length: 24
          dhcp: false
          enabled: true
        name: bond0.672
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 672
    nodeSelector:
      kubernetes.io/hostname: worker-0
- apiVersion: nmstate.io/v1
  kind: NodeNetworkConfigurationPolicy
  metadata:
    name: bond0
  spec:
    desiredState:
      interfaces:
      - link-aggregation:
          mode: 802.3ad
          port:
          - ens2f0
          - ens2f1
          - ens3f0
          - ens3f1
        name: bond0
        type: bond
      - name: bond0.677
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 677
      - bridge:
          port:
          - name: bond0.677
            vlan:
              mode: access
              tag: 677
        name: br-bond0.677
        state: up
        type: linux-bridge
      - name: bond0.58
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 58
      - bridge:
          port:
          - name: bond0.58
            vlan:
              mode: access
              tag: 58
        name: br-bond0.58
        state: up
        type: linux-bridge
      - name: bond0.59
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 59
      - bridge:
          port:
          - name: bond0.59
            vlan:
              mode: access
              tag: 59
        name: br-bond0.59
        state: up
        type: linux-bridge
kind: List
metadata:
  resourceVersion: ""
