- name: Check if ocp4.disconnected collection is installed
  ansible.builtin.command: ansible-galaxy collection list ocp4.disconnected
  register: collection_installed
  changed_when: false
  failed_when: false

- name: Test if connected to the internet
  ansible.builtin.uri:
    url: https://www.redhat.com
    method: GET
    status_code: 200
    validate_certs: false
  register: internet
  until: internet.status == 200
  retries: 2
  delay: 1
  failed_when: false
  when: 
    - "'ocp4.disconnected' not in collection_installed.stdout"
    - "update_collection | bool"

- name: Install ansible collections from local media
  ansible.builtin.command:
    cmd: "ansible-galaxy collection install -r requirements.yml"
  args:
    chdir: "{{ openshift_download_dir }}/collections"
  when:
    - "'ocp4.disconnected' not in collection_installed.stdout"
    - "(internet.status | default(0)) != 200"
  register: collection_install

- name: Install ansible collection from the internet
  ansible.builtin.command:
    cmd: ansible-galaxy collection install ocp4.disconnected
  when:
    - "'ocp4.disconnected' not in collection_installed.stdout"
    - "(internet.status | default(0)) != 200"
    - "update_collection | bool"
