{{- with .Values.nmstate }}

---

# Brings in the nmstate operator, installs it on the cluster.
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/kubernetes-nmstate-operator.openshift-nmstate: ""
  name: kubernetes-nmstate-operator
  namespace: {{ .target_namespace | default "openshift-nmstate" }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: {{ .channel | default "stable" }}
  installPlanApproval: Automatic
  name: kubernetes-nmstate-operator
  source: {{ .catalog_source | default "redhat-operators" }}
  sourceNamespace: {{ .sourceNamespace | default "openshift-marketplace" }}


{{- end }}