{{ if .Values.cluster.ca.specify }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-ca
  namespase: openshift-config
data:
  ca-bundle.crt: |
{{ .Values.cluster.ca.content | indent 4 }}
{{ else }}
# Did not specify cluster ca
{{ end }}