# Configures the ingress controller with the provided cert
# Cert specified in ingress-certs-secret.yaml
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  defaultCertificate:
    name: {{ .Values.cluster.ingress.secretName }}
