# Sets up syncing auth information with an LDAP server
apiVersion: v1
kind: LDAPSyncConfig
metadata:
  name: {{ .Values.ldap.syncConfigName }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
bindDN: {{ .Values.ldap.bindDN }}
bindPassword: {{ .Values.ldap.bindPW }}
insecure: true
url: {{ .Values.ldap.server.urlShort }}
groupUIDNameMapping:
{{ .Values.ldap.groupUIDNameMapping | indent 2 }}
augmentedActiveDirectory:
  groupUIDAttributes: dn
  groupNameAttributes: [ cn ]
  groupMembershipAttributes: [ memberOf ]
  userNameAttributes: [ {{ .Values.ldap.accountName }} ]
  groupsQuery:
    baseDN: "{{ .Values.ldap.queries.group.baseDN }}"
    scope: base
    derefAliases: never
    pagesize: 0
  usersQuery:
    baseDN: "{{ .Values.ldap.queries.user.baseDN }}"
    scope: sub
    derefAliases: never
    filter: {{ .Values.ldap.queries.user.filter }}
    pageSize: 0
