# The secret used to hold the password to talk to LDAP
# Used in ocp-oauth-sec.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ldap-bind-password
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "5"
data:
  bindPassword: {{ .Values.ldap.bindPW | b64enc }}
