# Defines the standard bond to use in the other nncps configuration
# Referenced in nncps.yaml
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond0
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  desiredState:
    interfaces:
      - name: bond0
        type: bond
        link-aggregation:
          mode: 802.3ad
          port: # TODO:: templatize?
            - ens2f0
            - ens2f1
            - ens3f0
            - ens3f1
