#!/usr/bin/ansible-playbook
- hosts: localhost
  roles:
    - ocp4.disconnected.common

- name: Create content directory
  ansible.builtin.file:
    path: "{{ drive }}/content"
    state: directory
    mode: '0755'
  become: true

- name: Copy generated content to drive
  ansible.builtin.copy:
    src: "{{ common_openshift_download_dir }}/content"
    dest: "" ## TODO Add drive here
  become: true


