#!/usr/bin/ansible-playbook -K
- hosts: localhost
  gather_facts: true
  roles:
    - role: import_collection
      tags: import_collection, always
    - role: ocp4.disconnected.worker_iso
      tags: always
    - role: ocp4.disconnected.media_share
      tags: idrac, stage_1
      when: media_share_idrac | bool
      vars:
        role: worker
