#!/usr/bin/ansible-playbook -K
- hosts: localhost
  roles:
    - ocp4.disconnected.install_binaries
    - ocp4.disconnected.package_check
    - ocp4.disconnected.registry
    - ocp4.disconnected.push_cluster_images
