---
- name: Monitor OpenShift Installation Status
  hosts: localhost
  gather_facts: no
  become: true
  
  vars:
    install_dir: "/ansible/isac/install-2024-08-06"  # Replace with your actual install directory
    log_level: "info"                   # Replace with desired log level
    bootstrap_complete_text: "bootstrap is complete" # standard text displayed by the openshift-install command
    oc_command: "oc get nodes --no-headers | awk '{print $2}' | grep Ready | wc -l" # gets the count of nodes in a ready state
    node_count: "4" #set to number of nodes in the cluster that needs to be marked 'ready' for a healthy deployment

  tasks:

    - name: Monitor OpenShift installation bootstrap process
      ansible.builtin.command:
        cmd: "openshift-install --dir {{ install_dir }} agent wait-for bootstrap-complete --log-level={{ log_level }}"
      register: bootstrap_output

    - name: Check status of cluster bootstrap
      debug:
        msg: "{{ bootstrap_output.stderr_lines[-1] }}"
      when: bootstrap_output.stderr is search( "{{bootstrap_complete_text}}")


    - name: Monitor node health
      ansible.builtin.shell:
        cmd: "{{ oc_command }}"
      register: node_status
      retries: 120
      delay: 15
      until: node_status.stdout == node_count
      when: bootstrap_output.stderr is search( "{{bootstrap_complete_text}}")

    - name: status
      ansible.builtin.debug:
        msg: "Node ready count is: {{node_status.stdout}}"
      when: node_status.stdout == node_count

